### ISSUE TITLE
Implement missing functions on windows 

### ISSUE THREAD

**Issue by lplewa** [oneapi-src/unified-memory-framework#568] opened 2024-06-26 12:10 UTC
Missing functions on windows should be implemented, and just return not supported return code.
Currently, we just do not export some linux only functions on windows.

**Comment by vinser52** [comment] 2024-06-26 12:43
Which API do you mean? Do we have a list?

**Comment by pbalcer** [comment] 2024-06-26 12:57
I think we should only ifdef things that will *never* work on Windows or use nix-specific things (like file descriptors). Things that are currently unimplemented (but will be eventually) should just fail at runtime.

**Comment by lplewa** [comment] 2024-06-26 13:07
> I think we should only ifdef things that will _never_ work on Windows or use nix-specific things (like file descriptors). Things that are currently unimplemented (but will be eventually) should just fail at runtime.

This is also an option. ATM we just do not provide symbol which is just _bad_

**Comment by lplewa** [comment] 2024-06-26 13:13
> Which API do you mean? Do we have a list?

```
$ diff <(grep -o '\bumf\w*' libumf.def.in | sort) <(grep -o '\bumf\w*' libumf.map | sort)

7a7
> umfLevelZeroMemoryProviderOps
29a30
> umfMemspaceCreateFromNumaArray
30a32,35
> umfMemspaceHighestBandwidthGet
> umfMemspaceHighestCapacityGet
> umfMemspaceHostAllGet
> umfMemspaceLowestLatencyGet
```

**Comment by lukaszstolarczuk** [comment] 2024-06-26 14:04
since this is about `.def` and `.map` files - isn't this related to/duplicate of https://github.com/oneapi-src/unified-memory-framework/issues/566 ?

**Comment by lplewa** [comment] 2024-06-26 14:16
> since this is about `.def` and `.map` files - isn't this related to/duplicate of #566 ?

No - this is only similar issue:

- those issue is about functions which was exported, but are not supposed to be exported. (internal function)
- this issue is about functions which are supposed to be exported but there are not

**Comment by vinser52** [comment] 2024-06-27 15:54
> umfLevelZeroMemoryProviderOps

LevelZero provider should be supported on Windows.

**Closed** 2024-10-25 12:46 UTC
Labels: bug
