### ISSUE TITLE
The umf_test-jemalloc_pool test segfaults with debug version of jemalloc

### ISSUE THREAD

**Issue by igchor** [oneapi-src/unified-memory-framework#161] opened 2024-01-18 18:14 UTC
**The current state:**

The `umf_test-jemalloc_pool` test segfaults with jemalloc v5.3.0 compiled with `--enable-debug`.

```
# ./test/umf_test-jemalloc_pool
base_alloc: allocation size (336) larger than the biggest allocation class. Falling back to OS memory allocation.
Running main() from /root/unified-memory-framework/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 16 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 1 test from test
[ RUN      ] test.metadataNotAllocatedUsingProvider
base_alloc: allocation size (152) larger than the biggest allocation class. Falling back to OS memory allocation.
Segmentation fault (core dumped)
```

-----------------------------------

**The original issue:**

When running with the latest version of jemalloc, build in debug mode we got the following output:

```
<jemalloc>: Should own 0 locks of rank >= 14: extent_grow(17)
Aborted (core dumped)
```

The problem seems to be caused by recursive call to jemalloc (we are calling malloc which is being intercepted withing extent hooks).

This can be solved by using a custom allocator for every allocation made inside extent hooks (this include critnib and tracking provider allocations).

**Comment by bratpiorka** [comment] 2024-01-26 16:44
JIRA UMFW-237

**Comment by ldorau** [comment] 2024-03-19 13:29
@igchor I cannot reproduce it now. Could you verify if it still exists and close this issue?

**Comment by igchor** [comment] 2024-03-19 17:14
It still fails for me for jemalloc, version 5.3.0_163 compiled with --enable-debug. However, I don't get that output anymore, there's just segfault now:

```
# ./test/umf_test-jemalloc_pool
base_alloc: allocation size (336) larger than the biggest allocation class. Falling back to OS memory allocation.
Running main() from /root/unified-memory-framework/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 16 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 1 test from test
[ RUN      ] test.metadataNotAllocatedUsingProvider
base_alloc: allocation size (152) larger than the biggest allocation class. Falling back to OS memory allocation.
Segmentation fault (core dumped)
```

**Comment by ldorau** [comment] 2024-03-20 06:56
@igchor Thanks!

**Comment by ldorau** [comment] 2024-03-20 09:36
**Solution:**

The `metadataNotAllocatedUsingProvider` test sets the memory protection to `UMF_PROTECTION_NONE`, because:

https://github.com/oneapi-src/unified-memory-framework/blob/0bdc5ded465f3a5b70524474a6f7f9b1608e6a62/test/pools/jemalloc_pool.cpp#L20-L31

but the **debug version of jemalloc always fills the allocated memory with a junk value**:

```c
static void default_junk_alloc(void *ptr, size_t usize) {
        memset(ptr, junk_alloc_byte, usize);
}
```

what causes the segfault.

Closing as "**works as expected**".

**Closed by ldorau** 2024-03-20 09:36 UTC
Labels: bug

**Comment by igchor** [comment] 2024-03-20 19:49
We could consider skipping this test for jemaloc if it's in debug mode (or detect whether jemalloc fills memory - I think this is possible through a ctl).
